=== eleo-jens/XML/Exos/Chapitre3/Schema/Exo2/Annuaire.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!--ELEMENT-->
    <xsd:element name="Annuaire" type="T_Annuaire" />
    <xsd:element name="Personne" type="T_Personne" />
    <xsd:element name="Sexe" type="T_HommeouFemme" />
    <xsd:element name="Nom" type="xsd:string" />
    <xsd:element name="Prenom" type="xsd:string" />
    <xsd:element name="Adresse" type="T_Adresse" />
    <xsd:element name="Rue" type="xsd:string" />
    <xsd:element name="Numero" type="xsd:positiveInteger" />
    <xsd:element name="Boite" type="xsd:positiveInteger" />
    <xsd:element name="CodePostal" type="T_CodePostal" />
    <xsd:element name="Ville" type="xsd:string" />
    <xsd:element name="Pays" type="xsd:string" />
    <xsd:element name="Telephones" type="T_Telephones"/>
    <xsd:element name="Telephone" type="T_Telephone"/>
    <xsd:element name="Courriels" type="T_Courriels"/>
    <xsd:element name="Courriel" type="T_Courriel"/>

    <!--TYPES-->
    <xsd:complexType name="T_Annuaire">
        <xsd:sequence>
            <xsd:element ref="Personne" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="T_Personne">
        <xsd:sequence>
            <xsd:element ref="Sexe" minOccurs="0" />
            <xsd:element ref="Nom" />
            <xsd:element ref="Prenom" maxOccurs="3" />
            <xsd:element ref="Adresse"/>
            <xsd:element ref="Telephones"/>
            <xsd:element ref="Courriels"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="T_HommeouFemme">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="F" />
            <xsd:enumeration value="H" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="T_Adresse">
        <xsd:sequence>
            <xsd:element ref="Rue" />
            <xsd:element ref="Numero" minOccurs="0" />
            <xsd:element ref="Boite" minOccurs="0" />
            <xsd:element ref="CodePostal" />
            <xsd:element ref="Ville" />
            <xsd:element ref="Pays" /> <!--voir pour une restriction pour rendre le pays en majuscule-->
        </xsd:sequence>
    </xsd:complexType>

    <xsd:simpleType name="T_CodePostal">
        <xsd:restriction base="xsd:positiveInteger">
            <xsd:minInclusive value="1000" />
            <xsd:maxInclusive value="9999" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="T_Telephones">
        <xsd:sequence>
            <xsd:element ref="Telephone" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="T_Telephone">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="T_Type" use="required"></xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:simpleType name="T_Type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Pro"/>
            <xsd:enumeration value="Perso"/>
            <xsd:enumeration value="Autre"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="T_Courriels">
        <xsd:sequence>
            <xsd:element ref="Courriel" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="T_Courriel">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="T_Type" use="required"></xsd:attribute>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

</xsd:schema>

=== eleo-jens/XML/Exos/Chapitre3/Schema/Exo2/Annuaire.xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>

<Annuaire
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Annuaire.xsd">
    <Personne>
        <Sexe>F</Sexe>
        <Nom>Jean</Nom>
        <Prenom>Katya</Prenom>
        <Adresse>
            <Rue>Rue de la cerise</Rue>
            <CodePostal>1150</CodePostal>
            <Ville>Bruxelles</Ville>
            <Pays>Belgique</Pays>
        </Adresse>
        <Telephones>
            <Telephone type="Perso">0495321456</Telephone>
            <Telephone type="Pro">026548963</Telephone>
        </Telephones>
        <Courriels></Courriels>
    </Personne>

    <Personne>
        <Sexe>H</Sexe>
        <Nom>Paul</Nom>
        <Prenom>Jean-Pail</Prenom>
        <Adresse>
            <Rue>Rue de la haie</Rue>
            <Numero>56</Numero>
            <Boite>123</Boite>
            <CodePostal>8000</CodePostal>
            <Ville>Charleroi</Ville>
            <Pays>Belgique</Pays>
        </Adresse>
        <Telephones>
            <Telephone type="Perso">0495321456</Telephone>
            <Telephone type="Pro">026548963</Telephone>
        </Telephones>
        <Courriels>
            <Courriel type="Pro">Jean-Pail.paul@oxfam.com</Courriel>
            <Courriel type="Perso">jpp8000@gmail.com</Courriel>
        </Courriels>
    </Personne>
</Annuaire>
