=== eleo-jens/XML/Démos/Schémas/Demo-SchemaInstance.xsd
<?xml version="1.1" encoding="UTF-8"?>
<!--ctrl espace NEW XML SCHEMA pour le snippet-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!--ELEMENT-->
    <xsd:element name="Interface3" type="T_Centre" />
    <xsd:element name="Classe" type="T_Cours" />
    <xsd:element name="Eleve" type="T_Personne" />
    <xsd:element name="Nom" type="xsd:string" />
    <xsd:element name="Prenom" type="xsd:string" />
    <xsd:element name="Contact" type="T_Contact" />
    <xsd:element name="Courriel" type="T_Courriel" />
    <xsd:element name="Telephone" type="xsd:string" />
    <!--TYPES-->
    <xsd:complexType name="T_Centre">
        <xsd:sequence>
            <xsd:element ref="Classe"></xsd:element> <!--reference à classe: va chercher l'élement qui s'appelle Classe-->
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="T_Personne">
        <xsd:sequence>
            <xsd:element ref="Nom" />
            <xsd:element ref="Prenom" />
            <xsd:element ref="Contact" />
        </xsd:sequence>
        <xsd:attribute name="genre" type="T_HommeOuFemme" use="required"/>
        <xsd:attribute name="age" type="T_Age" default="30"/>
    </xsd:complexType>
    <xsd:complexType name="T_Cours">
        <xsd:sequence>
            <xsd:element ref="Nom" />
            <xsd:element ref="Eleve" minOccurs="0" maxOccurs="15" />
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="T_Contact">
        <xsd:choice>
            <xsd:element ref="Courriel" minOccurs="1" maxOccurs="3" />
            <xsd:element ref="Telephone" />
        </xsd:choice>
    </xsd:complexType>
    <xsd:simpleType name="T_HommeOuFemme">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="H" />
            <xsd:enumeration value="F" />
        </xsd:restriction>
    </xsd:simpleType>
        <xsd:simpleType name="T_Age">
            <xsd:restriction base="xsd:positiveInteger">
                <xsd:minInclusive value="18" />
                <xsd:maxInclusive value="100" />
            </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="T_Courriel">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="type" type="T_CourrielChoice" use="required"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    </xsd:simpleType>
    <xsd:simpleType name="T_CourrielChoice">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="Pro"/>
            <xsd:enumeration value="Perso"/>
            <xsd:enumeration value="Autre"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== eleo-jens/XML/Démos/Schémas/Demo-SchemaInstance.XML
<?xml version="1.1" encoding="UTF-8" standalone="no"?>

<Interface3 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Demo-SchemaInstance.xsd">
    <Classe>
        <Nom>WAD</Nom>
        <Eleve genre="F" age="24">
            <Nom>Szymon</Nom>
            <Prenom>Menen</Prenom>
            <Contact>
                <Courriel type="Pro"></Courriel>
                <Courriel type="Perso"></Courriel>
            </Contact>
        </Eleve>
        <Eleve genre="F">
            <Nom>Rafaele</Nom>
            <Prenom>Alessandra</Prenom>
            <Contact>
                <Telephone></Telephone>
            </Contact>
        </Eleve>
        <Eleve genre="F">
            <Nom>Pehlivan</Nom>
            <Prenom>Sarah</Prenom>
            <Contact>
                <Telephone></Telephone>
            </Contact>
        </Eleve>
    </Classe>

</Interface3>
